FROM python:3.10.8
COPY . /app
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install confluent-kafka
RUN pip install requests
RUN pip install fastavro
RUN pip install jsonschema